"""
segmentation.py
---------------
Module for unsupervised customer segmentation using clustering algorithms
(K-Means, DBSCAN). Groups customers into behavioral segments such as
High-Value Loyalists, At-Risk Mid-Tier, and Low-Engagement One-Time Buyers
based on RFM features.

Pipeline:
    1. compute_rfm()           — Build Recency / Frequency / Monetary table
    2. scale_rfm()             — Log-transform + StandardScaler normalisation
    3. find_optimal_clusters() — Elbow + Silhouette analysis to choose k
    4. apply_kmeans()          — Fit K-Means and attach cluster labels
    5. label_segments()        — Map numeric clusters to business segment names
    6. save_rfm_segments()     — Persist the final labelled DataFrame

Usage:
    python src/segmentation.py
"""

import os
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

warnings.filterwarnings("ignore")

# Reference date: one day after the last transaction in the dataset
REFERENCE_DATE = pd.Timestamp("2011-12-10")

# Pre-defined segment labels for common k values (best -> worst).
# Always include the extremes; intermediate labels fill in as k grows.
# This ensures the second cluster is never mislabelled "Loyal Customers"
# when it is clearly dormant/low-value (e.g. k=2).
_K_LABEL_MAP: dict = {
    2: ["Champions",  "Dormant / At-Risk"],
    3: ["Champions",  "Potential Loyalists",  "Dormant / At-Risk"],
    4: ["Champions",  "Loyal Customers",      "At-Risk Customers",   "Lost / Hibernating"],
    5: ["Champions",  "Loyal Customers",      "Potential Loyalists", "At-Risk Customers", "Lost / Hibernating"],
}


def _get_segment_labels(n: int) -> list:
    """Return n ordered segment labels (best → worst) for any cluster count."""
    if n in _K_LABEL_MAP:
        return _K_LABEL_MAP[n]
    base = _K_LABEL_MAP[5]
    if n <= len(base):
        return base[:n]
    return base + [f"Segment {i + 1}" for i in range(n - len(base))]


# ---------------------------------------------------------------------------
# 1. COMPUTE RFM
# ---------------------------------------------------------------------------

def compute_rfm(df: pd.DataFrame) -> pd.DataFrame:
    """
    Build the RFM (Recency, Frequency, Monetary) table at the customer level.

    - Recency  : Days since the customer's last purchase, relative to
                 REFERENCE_DATE (2011-12-10). Lower = more recent = better.
    - Frequency: Number of unique invoices placed by the customer.
    - Monetary : Total revenue generated by the customer (sum of TotalPrice).

    Parameters
    ----------
    df : pd.DataFrame
        Cleaned retail DataFrame from Phase 1 (must contain InvoiceDate,
        Invoice, CustomerID, TotalPrice).

    Returns
    -------
    pd.DataFrame
        RFM table indexed by CustomerID.
    """
    rfm = (
        df.groupby("CustomerID")
        .agg(
            Recency  =("InvoiceDate", lambda x: (REFERENCE_DATE - x.max()).days),
            Frequency=("Invoice",     "nunique"),
            Monetary =("TotalPrice",  "sum"),
        )
    )

    print("\n" + "=" * 55)
    print("  RFM SUMMARY STATISTICS")
    print("=" * 55)
    print(rfm.describe().round(2).to_string())
    print(f"\n  Total customers in RFM table: {len(rfm):,}")
    print("=" * 55)

    return rfm


# ---------------------------------------------------------------------------
# 2. SCALE RFM
# ---------------------------------------------------------------------------

def scale_rfm(rfm: pd.DataFrame) -> tuple:
    """
    Reduce skewness and normalise the RFM features for clustering.

    Step 1 — Log transformation (np.log1p):
        Recency, Frequency, and Monetary are all right-skewed (especially
        Frequency and Monetary due to wholesale buyers). Log1p compresses
        extreme outliers while preserving relative ordering.

    Step 2 — StandardScaler:
        Centres and scales each feature to zero mean, unit variance so that
        K-Means (which is distance-based) treats each dimension equally.

    Parameters
    ----------
    rfm : pd.DataFrame
        Raw RFM table from compute_rfm().

    Returns
    -------
    rfm_scaled : np.ndarray
        Scaled feature matrix (n_customers x 3).
    scaler : sklearn.preprocessing.StandardScaler
        Fitted scaler (needed to invert transforms later if required).
    """
    print("\n" + "=" * 55)
    print("  FEATURE SCALING REPORT")
    print("=" * 55)

    print("  Skewness BEFORE log transform:")
    for col in ["Recency", "Frequency", "Monetary"]:
        print(f"    {col:<12}: {rfm[col].skew():.3f}")

    rfm_log = np.log1p(rfm[["Recency", "Frequency", "Monetary"]])

    print("\n  Skewness AFTER log transform:")
    for col in rfm_log.columns:
        print(f"    {col:<12}: {rfm_log[col].skew():.3f}")

    scaler = StandardScaler()
    rfm_scaled = scaler.fit_transform(rfm_log)

    print("\n  StandardScaler applied — features centred and scaled.")
    print("=" * 55)

    return rfm_scaled, scaler


# ---------------------------------------------------------------------------
# 3. FIND OPTIMAL CLUSTERS
# ---------------------------------------------------------------------------

def find_optimal_clusters(
    rfm_scaled: np.ndarray,
    output_dir: str = "data/processed",
) -> dict:
    """
    Determine the optimal number of K-Means clusters using two methods:

    - Elbow method  : Plot inertia (within-cluster sum of squares) vs k.
                      Look for the 'elbow' where the rate of decrease slows.
    - Silhouette    : Measures cluster cohesion and separation.
                      Score range: [-1, 1]; higher is better.
                      The k with the highest silhouette score is recommended.

    Plots are saved to `output_dir/elbow_silhouette.png`.

    Parameters
    ----------
    rfm_scaled : np.ndarray
        Scaled feature matrix from scale_rfm().
    output_dir : str
        Directory where the output PNG is saved.

    Returns
    -------
    dict
        {k: silhouette_score} for k in range(2, 11).
    """
    k_range   = range(2, 11)
    inertias  = []
    sil_scores = {}

    print("\n" + "=" * 55)
    print("  CLUSTER OPTIMISATION ANALYSIS  (k = 2 to 10)")
    print("=" * 55)
    print(f"  {'k':<4}  {'Inertia':>12}  {'Silhouette':>12}")
    print("  " + "-" * 34)

    for k in k_range:
        km     = KMeans(n_clusters=k, random_state=42, n_init=10)
        labels = km.fit_predict(rfm_scaled)
        inertias.append(km.inertia_)
        sil    = silhouette_score(rfm_scaled, labels)
        sil_scores[k] = sil
        print(f"  {k:<4}  {km.inertia_:>12,.0f}  {sil:>12.4f}")

    best_k = max(sil_scores, key=sil_scores.get)

    # --- Plot ---------------------------------------------------------------
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Elbow curve
    axes[0].plot(list(k_range), inertias, marker="o", color="steelblue",
                 linewidth=2, markersize=7)
    axes[0].set_title("Elbow Method — Inertia vs k", fontsize=13, fontweight="bold")
    axes[0].set_xlabel("Number of Clusters (k)")
    axes[0].set_ylabel("Inertia (WCSS)")
    axes[0].grid(True, alpha=0.3)
    axes[0].set_xticks(list(k_range))

    # Silhouette curve
    axes[1].plot(list(k_range), list(sil_scores.values()), marker="s",
                 color="coral", linewidth=2, markersize=7)
    axes[1].axvline(x=best_k, color="green", linestyle="--", alpha=0.8,
                    linewidth=1.5, label=f"Best k = {best_k}")
    axes[1].set_title("Silhouette Score vs k", fontsize=13, fontweight="bold")
    axes[1].set_xlabel("Number of Clusters (k)")
    axes[1].set_ylabel("Silhouette Score")
    axes[1].legend(fontsize=11)
    axes[1].grid(True, alpha=0.3)
    axes[1].set_xticks(list(k_range))

    fig.suptitle(
        "Determining Optimal Cluster Count — RFM Segmentation",
        fontsize=15, fontweight="bold", y=1.02,
    )
    plt.tight_layout()

    os.makedirs(output_dir, exist_ok=True)
    plot_path = os.path.join(output_dir, "elbow_silhouette.png")
    plt.savefig(plot_path, dpi=150, bbox_inches="tight")
    plt.close()

    print(f"\n  Recommended k (highest silhouette): {best_k}"
          f"  (score = {sil_scores[best_k]:.4f})")
    print(f"  Plot saved -> {plot_path}")
    print("=" * 55)

    return sil_scores


# ---------------------------------------------------------------------------
# 4. APPLY K-MEANS
# ---------------------------------------------------------------------------

def apply_kmeans(
    rfm: pd.DataFrame,
    rfm_scaled: np.ndarray,
    n_clusters: int,
) -> pd.DataFrame:
    """
    Fit K-Means with the specified number of clusters and attach labels.

    Parameters
    ----------
    rfm : pd.DataFrame
        Raw RFM table (used to attach the Cluster column).
    rfm_scaled : np.ndarray
        Scaled feature matrix from scale_rfm().
    n_clusters : int
        Number of clusters (use the k recommended by find_optimal_clusters).

    Returns
    -------
    pd.DataFrame
        RFM table with an added 'Cluster' integer column.
    """
    km = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    rfm = rfm.copy()
    rfm["Cluster"] = km.fit_predict(rfm_scaled)

    print("\n" + "=" * 55)
    print(f"  K-MEANS RESULTS  (k = {n_clusters})")
    print("=" * 55)
    sizes = rfm["Cluster"].value_counts().sort_index()
    for cluster_id, count in sizes.items():
        pct = count / len(rfm) * 100
        print(f"  Cluster {cluster_id}: {count:>5,} customers  ({pct:.1f}%)")
    print("=" * 55)

    return rfm


# ---------------------------------------------------------------------------
# 5. LABEL SEGMENTS
# ---------------------------------------------------------------------------

def label_segments(rfm: pd.DataFrame) -> pd.DataFrame:
    """
    Map numeric cluster IDs to descriptive business segment names.

    Labeling logic:
        1. Compute mean Recency, Frequency, and Monetary per cluster.
        2. Normalise each dimension to [0, 1] across clusters.
           Recency is inverted so that 1.0 = most recent (best).
        3. Compute an Overall RFM score = mean of the three normalised values.
        4. Rank clusters by Overall score (descending) and assign labels
           from _LABEL_POOL (Champions -> ... -> Lost / Hibernating).
        5. Override: if a cluster has high Recency score (recent) but very
           low Frequency score, it is relabelled as "New / Promising Customers"
           — they just arrived and haven't had time to become loyal yet.

    This approach is fully data-driven: labels reflect the ACTUAL relative
    behaviour of each cluster in this dataset.

    Parameters
    ----------
    rfm : pd.DataFrame
        RFM table with 'Cluster' column from apply_kmeans().

    Returns
    -------
    pd.DataFrame
        RFM table with an added 'Segment' string column.
    """
    cluster_means = rfm.groupby("Cluster")[["Recency", "Frequency", "Monetary"]].mean()

    # --- Normalise ----------------------------------------------------------
    def _norm(series: pd.Series, invert: bool = False) -> pd.Series:
        rng = series.max() - series.min()
        if rng == 0:
            return pd.Series(0.5, index=series.index)
        normalised = (series - series.min()) / rng
        return (1 - normalised) if invert else normalised

    cluster_means["R_score"] = _norm(cluster_means["Recency"],  invert=True)
    cluster_means["F_score"] = _norm(cluster_means["Frequency"], invert=False)
    cluster_means["M_score"] = _norm(cluster_means["Monetary"],  invert=False)
    cluster_means["Overall"] = (
        cluster_means["R_score"] +
        cluster_means["F_score"] +
        cluster_means["M_score"]
    ) / 3

    # --- Rank and assign base labels ----------------------------------------
    ranked     = cluster_means.sort_values("Overall", ascending=False)
    n          = len(ranked)
    label_pool = _get_segment_labels(n)

    label_map = {cluster_id: label_pool[rank]
                 for rank, cluster_id in enumerate(ranked.index)}

    # --- Override: "New / Promising Customers" ------------------------------
    # A cluster that is very recent (R_score >= 0.65) but very low frequency
    # (F_score <= 0.25) represents customers who joined recently and have not
    # yet had enough time to become repeat buyers.  Relabelling avoids
    # penalising them as "At-Risk" or "Lost" when they are actually promising.
    assigned = set(label_map.values())
    for cluster_id, row in ranked.iterrows():
        if (
            row["R_score"] >= 0.65
            and row["F_score"] <= 0.25
            and label_map[cluster_id] not in ("Champions",)
            and "New / Promising Customers" not in assigned
        ):
            assigned.discard(label_map[cluster_id])
            label_map[cluster_id] = "New / Promising Customers"
            assigned.add("New / Promising Customers")
            break

    rfm = rfm.copy()
    rfm["Segment"] = rfm["Cluster"].map(label_map)

    # --- Print summary ------------------------------------------------------
    print("\n" + "=" * 70)
    print("  SEGMENT SUMMARY")
    print("=" * 70)
    summary = (
        rfm.groupby("Segment")
        .agg(
            Customers   =("Recency",   "count"),
            Avg_Recency =("Recency",   "mean"),
            Avg_Frequency=("Frequency","mean"),
            Avg_Monetary=("Monetary",  "mean"),
        )
        .round(1)
    )
    summary["Pct_Base"] = (summary["Customers"] / len(rfm) * 100).round(1)
    summary = summary.sort_values("Avg_Monetary", ascending=False)
    print(summary.to_string())
    print("=" * 70)

    return rfm


# ---------------------------------------------------------------------------
# 6. SAVE RFM SEGMENTS
# ---------------------------------------------------------------------------

def save_rfm_segments(rfm: pd.DataFrame, output_path: str) -> None:
    """
    Persist the final labelled RFM DataFrame to a CSV file.

    Parameters
    ----------
    rfm : pd.DataFrame
        Labelled RFM table from label_segments().
    output_path : str
        File path for the output CSV (e.g. 'data/processed/rfm_segments.csv').
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    rfm.to_csv(output_path)
    print(f"\n[save_rfm_segments] Saved {len(rfm):,} rows -> {output_path}")


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    # --- Load cleaned data --------------------------------------------------
    df = pd.read_csv(
        "data/processed/cleaned_retail.csv",
        parse_dates=["InvoiceDate"],
    )

    # --- RFM pipeline -------------------------------------------------------
    rfm             = compute_rfm(df)
    rfm_scaled, _   = scale_rfm(rfm)
    sil_scores      = find_optimal_clusters(rfm_scaled)

    # Choose k with the highest silhouette score
    best_k = max(sil_scores, key=sil_scores.get)
    print(f"\n  Using k = {best_k} for final segmentation.")

    rfm = apply_kmeans(rfm, rfm_scaled, n_clusters=best_k)
    rfm = label_segments(rfm)
    save_rfm_segments(rfm, "data/processed/rfm_segments.csv")
